export interface Candidate {
  [x: string]: any;
  profissional: string;
  data_de_nascimento: string;
  cpf: string;
  cidade: string;
  uf: string;
  telefone: string;
  email: string;
  esta_empregado: string;
  empresa_atual: string;
  experiencia_ramo_automotivo: string;
  modalidade_atual: string;
  tipo_desejado_linkedin: string;
  nivel_funcao: string;
  formacao: string;
  interesse_imediato: string;
  entrevista_online: string;
  teste_tecnico: string;
  conhecimento_ingles: string;
  pretensao_salarial: string;
  pretensao_pj: string;
  cnpj: string;
  tipo_cnpj: string;
  // ultima_empresa: string;
  // ultimo_salario: string;
  vaga_100_presencial_porto_real_rj: string;
  vaga_100_presencial_goiana_pe: string;
  vaga_100_presencial_betim_mg: string;
  vaga_internacional: string;
  vaga_hibrida_betim: string;
  home_office: string;
  observacao: string;
  // status: string;
}
